version: "3"

tasks:
  start:
    cmds:
      - docker compose -f compose.yml up

  restore_postgres:
    cmds:
      - psql postgres://user:pass@localhost:15432/test < ./dumps/$(ls -1r ./dumps | head -n 1)
