name: Update Submodules

on:
  push:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Update Submodules
        run: git submodule update --remote --recursive

      - id: diff
        name: Check diff
        run: |
          git add -N .
          git diff --exit-code --quiet
        continue-on-error: true

      - name: Check docker compose build
        run: |
          touch .env.prod
          docker compose -f compose.yml build --progress=plain
        if: steps.diff.outcome == 'failure'

      - name: Commit files
        if: ${{ github.event_name != 'push' }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update submodules $(date +"%Y-%m-%d %H:%M:%S")"

      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
